version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-ec2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15mte4nmuhenv"
s3_prefix = "sam-app-ec2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
